export const basicSettings = {
  campaignName: "",
  campaignType: "",
  chanel: "",
  address: {
    address: "",
    sido: "",
    sigungu: "",
  },
  member: 1,
  campaignStartDate: "",
  campaignEndDate: "",
  campaignStatus: "",
  campaignBudget: "",
  campaignBudgetPeriod: "",
  campaignBudgetDaily: "",
  campaignBudgetWeekly: "",
  campaignBudgetMonthly: "",
  campaignBudgetYearly: "",
  additionalinfo: "",
  keywords: "",
  info: "",
  howtoregister: "",
  setToCompaign:false,
};
